name: Deploy Production

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: "mesmon-rg-dev"
  ACA_ENV_NAME: "mesmon-cae-dev"
  ACA_APP_NAME: "thumbnail-generator-service"

jobs:
  test:
    name: Safety Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun test

  build-and-deploy:
    needs: [test]
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/thumbnail-generator-app:${{ github.sha }}
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Image to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/thumbnail-generator-app:${{ github.sha }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ env.ACA_APP_NAME }}
          containerAppEnvironment: ${{ env.ACA_ENV_NAME }}
          targetPort: 3000
          ingress: external
          
          registryUrl: ${{ secrets.ACR_NAME }}.azurecr.io
          registryUsername: ${{ secrets.ACR_NAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}